baseURL = "https://fryboyter.de/"
DefaultContentLanguage = "de"
title = "fryboyter.de"
theme="fryboyter"
rssLimit = 20

[params]
  mainSections = ["posts"]
  ghrepo = "https://github.com/Fryboyter/Hugo/"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[languages]
    [languages.de]
        languageName = "Deutsche Version"
        languageCode = "de"
        weight = 1
    [languages.en]
        languageName = "English version"
        languageCode = "en"
        weight = 2

[permalinks]
  posts = ":slug"
