baseURL = "https://fryboyter.de/"
DefaultContentLanguage = "de"
languageCode = "de-de"
title = "fryboyter.de"
theme="fryboyter"
rssLimit = 20

[params]
  mainSections = ["posts"]

[languages]
    [languages.de]
        languageName = "Deutsche Version"
        weight = 1
    [languages.en]
        languageName = "English version"
        weight = 2

[permalinks]
  posts = ":slug"
